version: "3.3"
   
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  # selenium:
  #   image: selenium/standalone-chrome
  #   ports: 
  #     - "4444:4444"
  be:
    build: ./be
    command: python main.py
    volumes:
      - ./be:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
  fe:
    build: ./fe
    command: npm start
    volumes:
      - ./fe:/app
    ports:
      - "3000:3000"
    depends_on:
      - be
    env_file:
      - .env
